VDI Example Terraform
coreweave/kubernetes-cloud pull request #20
Opened 2021-07-14 08:34 UTC by jmarhee

Provides an example for cloud users to:

- Deploy a virtual desktop through Terraform via module
- An example for consuming the Terraform module

2021-07-14 08:43 UTC, jmarhee commented
This is re: https://github.com/coreweave/GTM-Requests/issues/82

2021-07-14 16:56 UTC, salanki commented
Please [use a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) in the description to link the PR to the [tracking issue](https://github.com/coreweave/infra-pm/issues/84). That way the issue gets auto closed and you can also see the PR when looking at the issue. I updated the description with this.

2021-07-14 17:03 UTC, salanki requested changes

2021-07-14 17:03 UTC, salanki commented on virtual-server/examples/terraform/vdi.tf
> +      "network" = {
Does it make sense to make this section configurable by the user as variables?

2021-07-14 17:03 UTC, salanki commented on virtual-server/examples/terraform/vdi.tf
> +          "count" = 3
This should be configurable just like GPU and RAM

2021-07-14 17:03 UTC, salanki commented on virtual-server/examples/terraform/vdi.tf
> +          "storageClassName" = "block-nvme-ord1"
The storage class name should be derived from the region. Ie, pseudocode: `block-nvme-${var.vdi_region}`.

2021-07-14 17:03 UTC, salanki commented
This is neat. I can see how this would evolve to Terraform modules provided by us.

2021-07-14 17:38 UTC, brianventuro commented on virtual-server/examples/terraform/README.md
> +This [terraform](terraform.io) module uses the [kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) to deploy `VirtualServers` (Virtual Desktops) to [CoreWe
coreweave.com

2021-07-16 15:57 UTC, salanki requested changes
Some minor tweaks left for consistency on Virtual Server / VS. Once this is merged, please add a description and link this repo as a new entry under "Deployment Methods" in the documentation, with some CLI examples how to run it. You can access gitbook where we edit our docs via login.CoreWeave.com

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/variables.tf
> +  description = "Namespace VDI will be installed to"
Change to Virtual Server

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/variables.tf
> +  default     = "MY-VDI"
VS

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/variables.tf
> +  description = "VDI username"
VS

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/variables.tf
> +  description = "VDI RAM"
VS

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/variables.tf
> +  description = "VDI root device storage (i.e 80Gi)"
VS

2021-07-16 15:57 UTC, salanki commented on virtual-server/examples/terraform/vs.tf
> +      "network" = {
Can we add in attachLoadBalancerIP here as well. It gets the Service IP directly attached to the VM (it becomes the Pod IP). It's a pretty common use case so good for completeness.

2021-07-19 17:33 UTC, salanki approved these changes
@jmarhee: Can you give me some example output how this looks on the CLI?

2021-07-19 17:45 UTC, jmarhee commented
> @jmarhee: Can you give me some example output how this looks on the CLI?

The Kubernetes provider requires the attributes this module outputs to be marked sensitive for CRDs via this resource type, so I can't print them out to STDOUT (but are exported so another module can consume them) but what I can do is update the output to add a output message/command for the client to get their password from the state (and the IP from `kubectl`) -- would that be sufficient here (and update the documentation to reflect that as well)?

2021-07-19 19:04 UTC, salanki commented
So there is something in the Kubernetes provider limiting you to fetch the IP address from the VS status? Can you explain that more, seems unreasonable, no way to disable? If we need to instruct users, they should be doing `kubectl get virtualserver` not go after the service directly.

2021-07-19 19:50 UTC, jmarhee commented
Yes, this is being enforced by at the provider level, [as I understood it](https://www.terraform.io/docs/language/values/outputs.html#sensitive-suppressing-values-in-cli-output), for this resource type's exports, but can confirm. 

I can access it via the output CLI command since that reads from the state directly where it is in clear text; I can definitely look into un-enforcing this, because that would be much more useful for a case like this where we want users to have the information they need without going back into kubectl to get it (or I can just direct users back to the virtualserver resource in kubectl to get, both, the IP and credentials, etc. etc.).

2021-07-19 19:51 UTC, jmarhee commented
Actually, I have another method I can try to get the information through Terraform (from the provider, rather than try to export something from the resource), I'll try that first, and then see about unenforcing the sensitive value rules.

2021-07-20 09:00 UTC, jmarhee commented
The last push includes the above-mentioned workaround for retrieving the VS password, and extracting the Service IP from the Kubernetes provider, sidestepping the provider-enforced resource attributes. 

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vs_network = "[address]"
vs_password = "[password]"
```

2021-07-20 19:39 UTC, salanki commented
Awesome. I'm gonna merge it, please write the docs in gitbook and close the tracking ticket once that is done!

2021-07-20 19:39 UTC, merged