Replace KServe with FastAPI for inference in finetuner example.
coreweave/kubernetes-cloud pull request #203
Opened 2023-05-25 15:21 UTC by harubaru

This PR replaces KServe's functionality with FastAPI for the sake of simplicity and allowing customers to get a better understanding of how to write an inference service on CoreWeave. Using KServe has a couple downsides, one of which is requiring package versions that conflicts with a key library being used such as [Tensorizer](https://github.com/coreweave/tensorizer).

This PR is to be added on top of #128.

2023-05-25 15:22 UTC, harubaru commented
One thing that needs to be done so far is to share sampling code with `evaluate.py`, since this gets inference to _just_ work with FastAPI.

2023-05-26 18:01 UTC, Eta0 requested changes
One required change (`async def` → `def`) and two nits. If you'd like me to whip up an `argparse` CLI for it I'd be happy to contribute one.

2023-05-26 18:01 UTC, Eta0 commented on finetuner-workflow/finetuner/inference.py
>  }
IMO using environment variables for this one while all of the other containers use command line arguments seems a little odd. Is there a particular reason to keep them this way, or just convenience?

2023-05-26 21:50 UTC, Eta0 approved these changes
Looks good 👍

2023-05-30 15:58 UTC, merged