HF LLM Overhaul
coreweave/kubernetes-cloud pull request #303
Opened 2023-12-20 20:44 UTC by harubaru

This PR adds a simple HuggingFace LLM inference server to the examples and it also removes the older and broken GPT-2 example. A majority of the code has been ported over from the Stable Diffusion inference service in order to provide a simple easy-to-use example as a way to introduce people to running inference servers on CoreWeave.

2023-12-21 00:03 UTC, Eta0 commented on online-inference/hf-llm/service/service.py
> +        return Response(content=str(e), media_type="text/plain", status_code=500)
You can provide more detail via the `logging` module while also preventing any information from leaking in server responses with something like this:
```suggestion
        import traceback

        logger.error(traceback.format_exc())
        return Response(
            content=(
                f"Server encountered an error of type {type(e).__name__}."
                "\nSee logs for details."
            ),
            media_type="text/plain",
            status_code=500,
        )
```

2023-12-21 00:22 UTC, harubaru commented on online-inference/hf-llm/serializer/requirements.txt
> +torch==2.0.0
I'll set it to `<2.3.0` since it might confuse users if a torch 3.0.0 exists lol

2023-12-21 00:33 UTC, wbrown commented on online-inference/hf-llm/serializer/requirements.txt
> +torch==2.0.0
I've had problems with it pulling down later torch'es if we don't specify exactly or use ~=

2023-12-21 01:05 UTC, Eta0 commented on online-inference/hf-llm/serializer/requirements.txt
> +torch==2.0.0
That's a generally a side effect of `pip install -U`/`pip install --upgrade`; upgrading will pull newer versions of `torch` whenever available, but regular `pip install` will keep the existing installed version unless it's incompatible with the other requirements.

2023-12-21 01:19 UTC, Eta0 requested changes

2023-12-21 01:19 UTC, Eta0 commented on online-inference/hf-llm/02-inference-service.yaml
This file needs its references to secrets updated to match the coalesced setup

2023-12-21 01:19 UTC, Eta0 commented on online-inference/hf-llm/Dockerfile
> +FROM ghcr.io/coreweave/ml-containers/torch:afecfe9-base-cuda11.8.0-torch2.0.0-vision0.15.1
The `ml-containers` Dockerfile currently uses torch-base with CUDA 12.0.1 (we could update these to a newer build too)

```suggestion
FROM ghcr.io/coreweave/ml-containers/torch:afecfe9-base-cuda12.0.1-torch2.0.0-vision0.15.1
```

2023-12-21 01:24 UTC, Eta0 commented on online-inference/hf-llm/service/service.py
> +    logger.info("Health check requested")
This shouldn't normally be necessary to know (and this event will be happening continuously) so this is fine as a debug log statement
```suggestion
    logger.debug("Health check requested")
```

2023-12-21 19:08 UTC, Eta0 requested changes
Testing it start-to-finish at the moment, noticed this in the meantime

2023-12-21 19:08 UTC, Eta0 commented on online-inference/hf-llm/02-inference-service.yaml
>                name: s3-host-url
```suggestion
              name: s3-credentials
```

2023-12-21 21:42 UTC, Eta0 requested changes
Added fixes for some issues in #306, please take a look.

2023-12-21 22:02 UTC, Eta0 commented
Seems all good once #306 is merged and the container image is updated to reflect the changes.
Noticed some weird inference behaviour in always getting the same results from prompts (and always extremely short ones when serving `--model-uri=EleutherAI/pythia-70m`, like the prompt unchanged or with one extra word), but the Kubernetes deployment itself and model loading are fine, so it'd be fine to merge for now and poke at that strangeness afterward.

2023-12-22 19:39 UTC, wbrown commented
> Seems all good once #306 is merged and the container image is updated to reflect the changes. Noticed some weird inference behaviour in always getting the same results from prompts (and always extremely short ones when serving `--model-uri=EleutherAI/pythia-70m`, like the prompt unchanged or with one extra word), but the Kubernetes deployment itself and model loading are fine, so it'd be fine to merge for now and poke at that strangeness afterward.
@Eta0 This is often a characteristic of sampling behaviors, especially when combined with very small models.

2023-12-22 19:40 UTC, wbrown commented
@Eta0 You need to resolve your requested change if we want to merge this.

2023-12-22 20:39 UTC, Eta0 commented
> @Eta0 You need to resolve your requested change if we want to merge this.

@wbrown Approve & merge coreweave/ml-containers#52 and I can update the image tag and approve it, that's the last thing that stills needs a change

2023-12-22 20:59 UTC, Eta0 approved these changes

2023-12-22 20:59 UTC, merged