feat(vso): Add ephemeral disk example
coreweave/kubernetes-cloud pull request #40
Opened 2021-12-30 11:29 UTC by goock

This PR adds an example with the ephemeral disk.

The disk is automatically formatted and mounted to `/mnt/vdb` via `cloud-init` script.

Additionally, I updated old root sources.

## Ref

fix https://github.com/coreweave/virtual-server-operator/issues/48

2022-07-11 16:37 UTC, YitzyD requested changes

2022-07-11 16:37 UTC, YitzyD commented on virtual-server/examples/kubectl/virtual-server-shared-pvc.yaml
> +          name: ubuntu2004-docker-master-20211208-ord1
ubuntu2004-docker-master-20220708-ord1

2022-07-11 16:37 UTC, YitzyD commented on virtual-server/examples/kubectl/virtual-server-ephemeral-disk.yaml
> +          name: ubuntu2004-docker-master-20211208-ord1
ubuntu1804-docker-master-20220708-ord1

2022-07-12 11:34 UTC, goock commented on virtual-server/examples/kubectl/virtual-server-block-pvc.yaml
> +          name: ubuntu2004-docker-master-20211208-ord1
All of them were nice and fresh but in Dec 2021 :D
They are updated.

2022-07-12 11:34 UTC, goock commented on virtual-server/examples/kubectl/virtual-server-ephemeral-disk.yaml
> +          name: ubuntu2004-docker-master-20211208-ord1
I think it should be Ubuntu 20.04

2022-07-12 11:39 UTC, goock commented on virtual-server/examples/kubectl/virtual-server-block-pvc.yaml
> +          name: ubuntu2004-nvidia-510-47-03-1-docker-master-20220517-ord1
We have GPU here, so I change the image to Nvidia.

2022-07-21 16:38 UTC, YitzyD approved these changes
Good to go. Confirmed ephemeral volumes are no concern.

2022-07-27 09:25 UTC, goock commented
@microcosem It looks like we do not have to do anything more for the doc with a new example, but I prefer just to let you know.

2022-07-27 09:25 UTC, merged

2022-07-28 15:11 UTC, microcosem commented
> @microcosem It looks like we do not have to do anything more for the doc with a new example, but I prefer just to let you know.

Thank you!!